<input type="date"<?=$this->getAttributesString(0)?> value="<?=$this->getFromValue()?>" title="From"/>
<input type="date"<?=$this->getAttributesString(1)?> value="<?=$this->getToValue()?>" title="To" />

<script>
	$(function(){
		$('#<?=$this->getId()?>-0,#<?=$this->getId()?>-1').change(function(e){
			var values = $('#<?=$this->getListId()?>-filters').serializeObject();
			
			$('#<?=$this->getListId()?>').waxrepeater('refresh', {
				page: 1,
				filters : values
			});

			setCookie('<?=$this->getListId()?>-filters', JSON.stringify(values));
		})
	})
</script>