<select<?=$this->getAttributesString()?>>
	<? foreach ($this->getOptions() as $key => $value): ?>
		<option value="<?=$key?>"><?=$value?></option>
	<? endforeach; ?>
</select>

<script>
	$(function(){
		$('#<?=$this->getId()?>').change(function(e){
			var values = $('#<?=$this->getListId()?>-filters').serializeObject();
			
			$('#<?=$this->getListId()?>').wxlist('refresh', {
				filters : values
			});
		})
	})
</script>