<input type="text"<?=$this->getAttributesString()?> value="<?=$this->getValue()?>" />

<script>
	$(function(){
		$('#<?=$this->getId()?>').keyup(function(e){
			if (e.which == 13 || e.keyCode == 13) {
				e.preventDefault();
				var values = $('#<?=$this->getListId()?>-filters').serializeObject();
			
				$('#<?=$this->getListId()?>').waxrepeater('refresh', {
					page: 1,
					filters : values
				});
			
				setCookie('<?=$this->getListId()?>-filters', JSON.stringify(values));
			}
		}).keydown(function(e){
			if (e.which == 13 || e.keyCode == 13) {
				e.preventDefault();
			}
		})
	})
</script>