<input type="text"<?=$this->getAttributesString()?> />

<script>
	$(function(){
		$('#<?=$this->getId()?>').keyup(function(e){
			if (e.which == 13 || e.keyCode == 13) {
				e.preventDefault();
				var values = $('#<?=$this->getListId()?>-filters').serializeObject();
			
				$('#<?=$this->getListId()?>').waxrepeater('refresh', {
					filters : values
				});
			}
		}).keydown(function(e){
			if (e.which == 13 || e.keyCode == 13) {
				e.preventDefault();
			}
		})
	})
</script>