<a href="<?=$this->createUrl('export')?>" class="btn btn-default" id="wax-export-list">{{ trans('cms.export.button_export') }}</a>

<script>
	$(function(){
		$('#wax-export-list').click(function(e){
			e.preventDefault();

			var filters = $('#slides-filters').serialize();
			var params = $.param($('#slides').waxrepeater('getParams'));

			location.href = $(this).attr('href') + '?' + filters + '&' + params;
		})
	})
</script>